apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::318258462434:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-F1g11F3LgVd9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::318258462434:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-18T10:53:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1275"
  uid: c800ed40-f912-4cc3-9af7-06f2fb4987d8
